#!/usr/bin/env python3
"""Generate rendered-markdown diff files under .markdowndiff/.

For each changed .md file between a git base ref and the working tree, emits a
sibling file containing the same markdown with inline <ins>/<del> HTML tags
highlighting additions and deletions. Open the result in IntelliJ's markdown
preview to see the rendered diff with green/red backgrounds.
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple

__version__ = "0.2.0"

GENERATED_HEADER = (
    "<!-- generated by markdowndiff — do not edit by hand -->\n"
)

INS_STYLE = (
    'style="background-color:rgba(46,160,67,0.12);'
    "border-left:3px solid rgba(46,160,67,0.5);"
    "padding:0.2em 2px 0.2em 6px;text-decoration:none;"
    "-webkit-box-decoration-break:clone;box-decoration-break:clone\""
)
DEL_STYLE = (
    'style="background-color:rgba(248,81,73,0.12);'
    "border-left:3px solid rgba(248,81,73,0.5);"
    "padding:0.2em 2px 0.2em 6px;text-decoration:line-through;"
    "-webkit-box-decoration-break:clone;box-decoration-break:clone\""
)
BLOCK_ADDED_STYLE = (
    'style="border-left:4px solid #2d7a33;padding-left:8px;margin:8px 0"'
)
BLOCK_REMOVED_STYLE = (
    'style="border-left:4px solid #c24a4a;padding-left:8px;margin:8px 0;'
    'opacity:0.75"'
)
BLOCK_MODIFIED_STYLE = (
    'style="border-left:4px solid #d29922;padding-left:8px;margin:8px 0"'
)
TOKEN_RE = re.compile(r'(\s+|[*_`\[\]()#~|>!-])')
FENCE_RE = re.compile(r'^\s{0,3}(```|~~~)')
BLOCK_PREFIX_RE = re.compile(
    r'^(\s{0,3}(?:#{1,6}\s+|[-*+]\s+|\d+[.)]\s+|>\s?))(.+)$'
)
WORD_DIFF_RATIO_THRESHOLD = 0.6


def is_fence_line(line: str) -> bool:
    return bool(FENCE_RE.match(line))


def split_block_prefix(line: str) -> tuple[str, str]:
    m = BLOCK_PREFIX_RE.match(line)
    if m:
        return m.group(1), m.group(2)
    return "", line


def run_git(args: list[str], cwd: Path) -> tuple[int, str]:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode, result.stdout


def repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("error: git is not installed or not on PATH")
    except subprocess.CalledProcessError:
        sys.exit("error: not inside a git repository")
    return Path(result.stdout.strip())


def verify_ref(ref: str, root: Path) -> None:
    code, _ = run_git(["rev-parse", "--verify", "--quiet", ref], root)
    if code != 0:
        sys.exit(f"error: base ref '{ref}' is not a valid git reference")


def find_changed_md_files(base: str, root: Path, paths: list[str]) -> list[str]:
    pathspec = ["--", *paths] if paths else []
    _, tracked = run_git(["diff", "--name-only", base, *pathspec], root)
    _, untracked = run_git(
        ["ls-files", "--others", "--exclude-standard", *pathspec], root
    )
    files = set()
    for line in (tracked + untracked).splitlines():
        line = line.strip()
        if line.lower().endswith(".md"):
            files.add(line)
    return sorted(files)


def get_old_content(path: str, base: str, root: Path) -> str:
    _, out = run_git(["show", f"{base}:{path}"], root)
    return out


def get_new_content(path: str, root: Path) -> str:
    abs_path = root / path
    if abs_path.exists():
        return abs_path.read_text(encoding="utf-8")
    return ""


def tokenize_line(line: str) -> list[str]:
    return [t for t in TOKEN_RE.split(line) if t != ""]


def wrap_ins(text: str) -> str:
    return f"<ins {INS_STYLE}>{text}</ins>" if text else ""


def wrap_del(text: str) -> str:
    return f"<del {DEL_STYLE}>{text}</del>" if text else ""


def is_table_row(line: str) -> bool:
    s = line.strip()
    return len(s) >= 2 and s.startswith("|") and s.endswith("|")


def is_table_separator_row(line: str) -> bool:
    s = line.strip()
    if not (s.startswith("|") and s.endswith("|")):
        return False
    inner = s[1:-1]
    return inner != "" and all(c in "-: |" for c in inner) and "-" in inner


def wrap_table_row(line: str, wrapper) -> str:
    stripped = line.rstrip("\n")
    parts = stripped.split("|")
    out = [parts[0]]
    for cell in parts[1:-1]:
        content = cell.strip()
        if not content:
            out.append(cell)
            continue
        leading = cell[: len(cell) - len(cell.lstrip())]
        trailing = cell[len(cell.rstrip()):]
        out.append(f"{leading}{wrapper(content)}{trailing}")
    out.append(parts[-1])
    return "|".join(out)


def wrap_line(line: str, wrapper) -> str:
    if is_table_separator_row(line):
        return line
    if is_table_row(line):
        return wrap_table_row(line, wrapper)
    prefix, content = split_block_prefix(line)
    if prefix:
        return f"{prefix}{wrapper(content)}"
    return wrapper(line)


def should_word_diff(old_line: str, new_line: str) -> bool:
    if "`" in old_line or "`" in new_line:
        return False
    return difflib.SequenceMatcher(
        a=old_line, b=new_line, autojunk=False
    ).ratio() >= WORD_DIFF_RATIO_THRESHOLD


def inline_word_diff(old_line: str, new_line: str) -> str:
    old_toks = tokenize_line(old_line)
    new_toks = tokenize_line(new_line)
    matcher = difflib.SequenceMatcher(a=old_toks, b=new_toks, autojunk=False)
    out: list[str] = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            out.append("".join(new_toks[j1:j2]))
        elif tag == "delete":
            out.append(wrap_del("".join(old_toks[i1:i2])))
        elif tag == "insert":
            out.append(wrap_ins("".join(new_toks[j1:j2])))
        elif tag == "replace":
            out.append(wrap_del("".join(old_toks[i1:i2])))
            out.append(wrap_ins("".join(new_toks[j1:j2])))
    return "".join(out)


def find_uniform_fence_regions(
    lines: list[str], status: list[str], target_statuses: set[str]
) -> dict[int, int]:
    regions: dict[int, int] = {}
    i = 0
    while i < len(lines):
        if is_fence_line(lines[i]):
            j = i + 1
            while j < len(lines) and not is_fence_line(lines[j]):
                j += 1
            if j < len(lines) and all(
                status[k] in target_statuses for k in range(i, j + 1)
            ):
                regions[i] = j
            i = j + 1 if j < len(lines) else i + 1
        else:
            i += 1
    return regions


class FenceMap(NamedTuple):
    """Bundles a fence-region mapping plus its derived lookup sets."""

    starts: dict[int, int]
    indices: frozenset[int]
    ends: frozenset[int]

    @classmethod
    def build(cls, starts: dict[int, int]) -> "FenceMap":
        return cls(
            starts=dict(starts),
            indices=frozenset(
                k for s, e in starts.items() for k in range(s, e + 1)
            ),
            ends=frozenset(starts.values()),
        )


def map_old_to_new_index(old_i: int, opcodes) -> int | None:
    for tag, i1, i2, j1, j2 in opcodes:
        if tag == "equal" and i1 <= old_i < i2:
            return j1 + (old_i - i1)
    return None


def find_modified_fence_regions(
    lines: list[str], status: list[str]
) -> dict[int, int]:
    regions: dict[int, int] = {}
    i = 0
    while i < len(lines):
        if is_fence_line(lines[i]):
            j = i + 1
            while j < len(lines) and not is_fence_line(lines[j]):
                j += 1
            if (
                j < len(lines)
                and status[i] == "equal"
                and status[j] == "equal"
                and any(status[k] != "equal" for k in range(i + 1, j))
            ):
                regions[i] = j
            i = j + 1 if j < len(lines) else i + 1
        else:
            i += 1
    return regions


def diff_to_markdown(old: str, new: str) -> str:
    old_lines = old.splitlines()
    new_lines = new.splitlines()
    opcodes = difflib.SequenceMatcher(
        a=old_lines, b=new_lines, autojunk=False
    ).get_opcodes()

    new_status = ["equal"] * len(new_lines)
    old_status = ["equal"] * len(old_lines)
    for tag, i1, i2, j1, j2 in opcodes:
        if tag == "insert":
            for j in range(j1, j2):
                new_status[j] = "insert"
        elif tag == "delete":
            for i in range(i1, i2):
                old_status[i] = "delete"
        elif tag == "replace":
            for j in range(j1, j2):
                new_status[j] = "replace-new"
            for i in range(i1, i2):
                old_status[i] = "replace-old"

    added = FenceMap.build(
        find_uniform_fence_regions(
            new_lines, new_status, {"insert", "replace-new"}
        )
    )
    removed = FenceMap.build(
        find_uniform_fence_regions(
            old_lines, old_status, {"delete", "replace-old"}
        )
    )
    modified_starts = dict(
        find_modified_fence_regions(new_lines, new_status)
    )
    for old_start, old_end in find_modified_fence_regions(
        old_lines, old_status
    ).items():
        new_start = map_old_to_new_index(old_start, opcodes)
        new_end = map_old_to_new_index(old_end, opcodes)
        if (
            new_start is not None
            and new_end is not None
            and new_start not in added.starts
            and new_start not in modified_starts
        ):
            modified_starts[new_start] = new_end
    modified = FenceMap.build(modified_starts)

    out: list[str] = []
    # in_fence tracks the OUTPUT stream's fence state (toggled as we emit
    # fence markers) — not the source file's. Inside a fence we suppress
    # del/ins wrapping because HTML tags don't render in code blocks.
    in_fence = False

    def emit_new(j: int, line: str, wrapper=None) -> None:
        nonlocal in_fence
        if j in added.starts:
            out.append(f"<div {BLOCK_ADDED_STYLE}>")
            out.append("")
        elif j in modified.starts:
            out.append(f"<div {BLOCK_MODIFIED_STYLE}>")
            out.append("")
        if j in added.indices:
            out.append(line)
            if is_fence_line(line):
                in_fence = not in_fence
        elif is_fence_line(line):
            out.append(line)
            in_fence = not in_fence
        elif in_fence:
            out.append(line)
        elif wrapper is None:
            out.append(line)
        else:
            out.append(wrap_line(line, wrapper))
        if j in added.ends or j in modified.ends:
            out.append("")
            out.append("</div>")

    def emit_old_delete(i: int, line: str) -> None:
        nonlocal in_fence
        if i in removed.starts:
            out.append(f"<div {BLOCK_REMOVED_STYLE}>")
            out.append("")
        if i in removed.indices:
            out.append(line)
            if is_fence_line(line):
                in_fence = not in_fence
        elif in_fence:
            pass
        else:
            out.append(wrap_line(line, wrap_del))
        if i in removed.ends:
            out.append("")
            out.append("</div>")

    for tag, i1, i2, j1, j2 in opcodes:
        if tag == "equal":
            for j in range(j1, j2):
                emit_new(j, new_lines[j])
        elif tag == "insert":
            for j in range(j1, j2):
                emit_new(j, new_lines[j], wrap_ins)
        elif tag == "delete":
            for i in range(i1, i2):
                emit_old_delete(i, old_lines[i])
        elif tag == "replace":
            if (
                (i2 - i1) == 1
                and (j2 - j1) == 1
                and not in_fence
                and not is_fence_line(old_lines[i1])
                and not is_fence_line(new_lines[j1])
                and should_word_diff(old_lines[i1], new_lines[j1])
            ):
                out.append(inline_word_diff(old_lines[i1], new_lines[j1]))
            else:
                old_row_idxs = [
                    i for i in range(i1, i2) if is_table_row(old_lines[i])
                ]
                old_other_idxs = [
                    i for i in range(i1, i2) if not is_table_row(old_lines[i])
                ]
                new_row_idxs = [
                    j for j in range(j1, j2) if is_table_row(new_lines[j])
                ]
                new_other_idxs = [
                    j for j in range(j1, j2) if not is_table_row(new_lines[j])
                ]
                for i in old_row_idxs:
                    emit_old_delete(i, old_lines[i])
                for j in new_row_idxs:
                    emit_new(j, new_lines[j], wrap_ins)
                had_rows = bool(old_row_idxs or new_row_idxs)
                had_other = bool(old_other_idxs or new_other_idxs)
                if had_rows and had_other and out and out[-1] != "":
                    out.append("")
                for i in old_other_idxs:
                    if not old_lines[i].strip():
                        continue
                    emit_old_delete(i, old_lines[i])
                for j in new_other_idxs:
                    emit_new(j, new_lines[j], wrap_ins)
    trailing = "\n" if (new.endswith("\n") or old.endswith("\n")) else ""
    return "\n".join(out) + trailing


def process_file(path: str, base: str, root: Path, out_dir: Path) -> bool:
    old = get_old_content(path, base, root)
    new = get_new_content(path, root)
    if not old and not new:
        return False
    content = GENERATED_HEADER + diff_to_markdown(old, new)
    out_path = out_dir / path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return True


def cleanup_stale(out_dir: Path, written: set[Path]) -> list[Path]:
    if not out_dir.exists():
        return []
    removed: list[Path] = []
    for p in out_dir.rglob("*.md"):
        if p not in written:
            p.unlink()
            removed.append(p)
    for d in sorted(
        (p for p in out_dir.rglob("*") if p.is_dir()),
        key=lambda p: len(p.parts),
        reverse=True,
    ):
        try:
            d.rmdir()
        except OSError:
            pass
    return removed


def resolve_base(
    args: argparse.Namespace, root: Path, mode_file: Path
) -> tuple[str, str]:
    """Return (base_ref, human_label) for the current invocation.

    Precedence: --branch > --base > persisted .mode file > auto-detect
    (on trunk → HEAD; elsewhere → merge-base with trunk).
    """
    if args.branch:
        use_branch_mode = True
    elif args.base is not None:
        use_branch_mode = False
    elif mode_file.exists():
        saved = mode_file.read_text(encoding="utf-8").strip()
        if saved == "branch":
            use_branch_mode = True
        elif saved == "uncommitted":
            use_branch_mode = False
        else:
            _, current = run_git(["rev-parse", "--abbrev-ref", "HEAD"], root)
            use_branch_mode = current.strip() != args.trunk
    else:
        _, current = run_git(["rev-parse", "--abbrev-ref", "HEAD"], root)
        use_branch_mode = current.strip() != args.trunk

    if use_branch_mode:
        code, merge_base = run_git(["merge-base", "HEAD", args.trunk], root)
        merge_base = merge_base.strip()
        if code != 0 or not merge_base:
            sys.exit(
                f"error: could not compute merge-base with '{args.trunk}'"
            )
        return merge_base, f"merge-base with {args.trunk} ({merge_base[:8]})"
    base = args.base or "HEAD"
    verify_ref(base, root)
    return base, base


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate rendered-markdown diff files. For each changed .md "
            "file between <base> and the working tree, write a sibling file "
            "under <output>/ containing the same markdown with inline "
            "<ins>/<del> HTML tags highlighting additions and deletions. "
            "Open the result in IntelliJ's markdown preview to see the "
            "rendered diff with green/red backgrounds."
        )
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    parser.add_argument(
        "--base",
        default=None,
        help=(
            "Git ref to compare the working tree against. Overrides the "
            "auto-detected default and the persistent mode file."
        ),
    )
    parser.add_argument(
        "--branch",
        action="store_true",
        help=(
            "Compare against the merge-base with <trunk>, showing everything "
            "that changed on this branch. Overrides --base."
        ),
    )
    parser.add_argument(
        "--trunk",
        default="main",
        help="Trunk branch used by --branch and auto-detect (default: main).",
    )
    parser.add_argument(
        "--output",
        default=".markdowndiff",
        help="Output directory relative to the repo root (default: .markdowndiff).",
    )
    mode_ops = parser.add_mutually_exclusive_group()
    mode_ops.add_argument(
        "--set-mode",
        choices=["uncommitted", "branch", "auto"],
        help=(
            "Persist a default mode in <output>/.mode and exit without "
            "regenerating. 'auto' removes the file so auto-detect resumes."
        ),
    )
    mode_ops.add_argument(
        "--show-mode",
        action="store_true",
        help="Print the persisted mode (or 'auto' if no mode file) and exit.",
    )
    verbosity = parser.add_mutually_exclusive_group()
    verbosity.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Suppress per-file progress and summary output (errors still print).",
    )
    verbosity.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="List each stale file that cleanup removed.",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Optional pathspecs to limit which files are processed.",
    )
    args = parser.parse_args()

    root = repo_root()
    out_dir = root / args.output
    mode_file = out_dir / ".mode"

    def say(msg: str) -> None:
        if not args.quiet:
            print(msg)

    if args.show_mode:
        if mode_file.exists():
            print(mode_file.read_text(encoding="utf-8").strip())
        else:
            print("auto")
        return 0

    if args.set_mode:
        if args.set_mode == "auto":
            if mode_file.exists():
                mode_file.unlink()
                say(f"Mode reset to auto (removed {mode_file}).")
            elif args.verbose:
                print("Mode already auto (no mode file present).")
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            mode_file.write_text(args.set_mode + "\n", encoding="utf-8")
            say(f"Mode set to '{args.set_mode}' (wrote {mode_file}).")
        return 0

    base, base_label = resolve_base(args, root, mode_file)

    files = find_changed_md_files(base, root, args.paths)

    written: set[Path] = set()
    for path in files:
        if process_file(path, base, root, out_dir):
            written.add(out_dir / path)
            say(f"  {path} -> {args.output}/{path}")

    removed: list[Path] = []
    if not args.paths:
        removed = cleanup_stale(out_dir, written)

    if args.verbose and removed:
        for p in removed:
            try:
                rel = p.relative_to(root)
            except ValueError:
                rel = p
            print(f"  removed stale {rel}")

    if not written and not removed:
        say(f"No changed .md files found vs {base_label}.")
        return 0

    parts = []
    if written:
        parts.append(f"Wrote {len(written)} file(s)")
    if removed:
        parts.append(f"removed {len(removed)} stale file(s)")
    say(f"{', '.join(parts)} in {args.output}/ (vs {base_label})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
