"""HTML/CSS constants used by the diff output."""

from __future__ import annotations

GENERATED_HEADER = (
    "<!-- generated by markdowndiff — do not edit by hand -->\n"
)

INS_STYLE = (
    'style="background-color:rgba(46,160,67,0.12);'
    "border-left:3px solid rgba(46,160,67,0.5);"
    "padding:0.2em 2px 0.2em 6px;text-decoration:none;"
    "-webkit-box-decoration-break:clone;box-decoration-break:clone\""
)
DEL_STYLE = (
    'style="background-color:rgba(248,81,73,0.12);'
    "border-left:3px solid rgba(248,81,73,0.5);"
    "padding:0.2em 2px 0.2em 6px;text-decoration:line-through;"
    "-webkit-box-decoration-break:clone;box-decoration-break:clone\""
)
BLOCK_ADDED_STYLE = (
    'style="border-left:4px solid #2d7a33;padding-left:8px;margin:8px 0"'
)
BLOCK_REMOVED_STYLE = (
    'style="border-left:4px solid #c24a4a;padding-left:8px;margin:8px 0;'
    'opacity:0.75"'
)
BLOCK_MODIFIED_STYLE = (
    'style="border-left:4px solid #d29922;padding-left:8px;margin:8px 0"'
)
